/**
 * Common error codes used across the application
 */
export enum ErrorCodes {
  NOT_FOUND = 'NOT_FOUND',
  MISSING_CREDENTIALS = 'MISSING_CREDENTIALS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_INVITATION_TOKEN = 'INVALID_INVITATION_TOKEN',
  INVITATION_EMAIL_MISMATCH = 'INVITATION_EMAIL_MISMATCH',
  DATABASE_CONNECTION_NOT_CONFIGURED = 'DATABASE_URL_NOT_CONFIGURED',
  JWT_CONFIGURATION_ERROR = 'JWT_CONFIGURATION_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  HTTP_ERROR = 'HTTP_ERROR',
  NO_DATA = 'NO_DATA',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVITATION_ALREADY_USED = 'INVITATION_ALREADY_USED',
  PROJECT_LAST_ADMIN_ERROR = 'PROJECT_LAST_ADMIN_ERROR',
  PROJECT_ALREADY_MEMBER_ERROR = 'PROJECT_ALREADY_MEMBER_ERROR'
}



